package uk.ac.sussex.asegr3.client;

import org.junit.Before;
import org.junit.Test;

/**
 * This test is purely to satify cobertura with the autogenerated classes
 * @author andrewhaines
 *
 */
public class RUnitTest {

	private R candidate;
	
	@Before
	public void before(){
		candidate = new R();
	}
	
	@Test
	public void satifyCobortura(){
		new R.attr();
		new R.drawable();
		new R.id();
		new R.layout();
		new R.string();
	}
	
}
